services:
  node:
    build: .
    container_name: container-node
    command: npm run dev
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - /app/node_modules
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      PG_USER: root
      PG_PASSWORD: password
      PG_HOST: db
      PG_DATABASE: loja-agilstore
      PG_PORT: 5432
      PORT: 5333
    restart: unless-stopped

  db:
    container_name: db-container
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: loja-agilstore
    env_file:
      - .env
